[package]
name = "wit-text"
publish = false
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
#rand_core = "0.6.4"
#fastrand = { version = "2.0.1" }
num-traits = "0.2.17"
num-bigint = "0.4.4"
wit-bindgen = "0.13.0"


[dev-dependencies]

[features]
default = []
