[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/wit-image",
    "projects/wit-number",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
