package vit:text


interface ascii {
    record ascii {
        codepoint: u8,
    }

    resource ascii-text {
        get-char-offset: func(offset: u64) -> option<ascii>
    }
}

world ascii-ffi {
    export ascii
}
