[package]
name = "wit-test"
publish = false
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
itertools = "0.12.1"
wasmtime = { version = "20.0.2", features = ["component-model"] }
wasmtime-wasi = { version = "20.0.2", features = [] }

[dev-dependencies]

[features]
default = []
