[package]
name = "wit-test"
publish = false
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmtime = "14.0.3"
wasmtime-wasi = "14.0.3"


[dev-dependencies]

[features]
default = []
