package vit:core

world core {
    import print: func(msg: string)

    export run: func()
}

interface my-interface {
    // use wasi:http/types@1.0.0.{request, response};
}

world my-world {
//    import wasi:filesystem/filesystem;
//    import wasi:random/random;
//    import wasi:http/handler@1.0.0;
//    export wasi:http/handler@1.0.0; wit add wasi:filesystem
}