package vit:core

world ffi {
     include integer-ffi;
//    import wasi:filesystem/filesystem;
//    import wasi:random/random;
//    import wasi:http/handler@1.0.0;
//    export wasi:http/handler@1.0.0; wit add wasi:filesystem
//    import print: func(msg: string)
//    import self/def-integer
}
