package vit:core

interface def-integer {
    record int {
        x: list<u32>,
    }
    get-position: func() -> int
    set-position: func(pos: int)
    monsters: func() -> list<int>

    // export run: func()
}

world integer {
    export def-integer
//    import wasi:filesystem/filesystem;
//    import wasi:random/random;
//    import wasi:http/handler@1.0.0;
//    export wasi:http/handler@1.0.0; wit add wasi:filesystem
      import print: func(msg: string)
//    import self/def-integer
}
