package vit:image

interface rgba-image {
    record rgba-pixel {
        r: u8,
        g: u8,
        b: u8,
        a: u8,
    }
    /// unsigned integer buffer
    resource rgba-image {
        constructor(init: list<u32>);
        new-w-h: func(w: u32, h: u32) -> rgba-image;
        decode-png: static func(bytes: list<u8>) -> rgba-image;


        get-pixel: func(x: u32, y: u32) -> rgba-pixel;
        set-pixel: func(x: u32, y: u32, p: rgba-pixel);



    }
}
