[package]
name = 'valkyrie-native'
version = '0.1.0'
description = 'Description for package valkyrie-wit'

# See more keys and definitions at https://docs.wasmer.io/registry/manifest

[[module]]
name = 'vit:native'
source = 'valkyrie-native.wasm'
abi = 'wasi'

[module.interfaces]
wasi = '0.1.0-unstable'


